name: PR Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install

      - name: Prettier & ESLint Check
        run: pnpm lint

      - name: Install Playwright Browsers
        run: pnpm exec playwright install

      - name: Playwright & vitest Check
        run: pnpm test

      - name: Svelte Check
        run: pnpm check

      - name: Build Check
        run: pnpm build
